<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="/img/favicon.png" />
        
        <?= $this->headTitle(), $this->headMeta(), $this->headLink(), $this->headScript(); ?>
        
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php if ($this->isTakeOver === true) : ?>
        <div class="text-center" style="font-size: 12px;background: #000;color: #fff">
            En cours de prise de contrôle de
            <b>"<?php echo $account->getFirstname().' '.$account->getLastname()?>"</b>
            <a href="<?= $this->url('administration-account/end-take-over'); ?>">Quitter la session</a>
        </div>
        <?php endif;?>
        <div id="header" class="header header-gestion">
            <div class="container" style="position: relative;">
                <div class="header-logo">
                    <a href="<?= $this->url('professionnal-dashboard'); ?>" title="Retour au tableau de bord">
                        <span class="logo">Hairlov</span>
                        <span class="slogan">Coiffeurs privés</span>
                    </a>
                </div>
                <a href="<?= $this->url('application-home') ?>" class="btn btn-default pull-right mg-t hidden-xs" style="position: absolute; right: 0">Accès public</a>
            </div>
        </div>
        <nav class="navbar navbar-gestion navbar-default hidden-lg">
            <div class="container">
                <div class="navbar-header hidden-lg">
                    <button type="button" class="navbar-toggle navbar-button collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Afficher la navigation</span>
                        <div class="pull-left menu-text">MENU</div>
                        <div class="pull-right">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </div>
                    </button>
                    <button type="button" class="btn btn-link navbar-button collapsed" data-toggle="collapse" data-target="#account-navbar" aria-expanded="false" aria-controls="navbar">
                        <?php if($account->getAccountImageFilename() !== null): ?>
                        <img src="<?= $this->url('application-load-image', [
                            'category' => 'account-image',
                            'idImage' => $account->getAccountImageFilename(),
                            'width' => '36',
                            'height' => '36'
                        ]); ?>" width="36" class="img-circle" />
                        <?php else: ?>
                        <img src="/img/avatar.jpg" width="36" class="img-circle" />
                        <?php endif; ?>
                        <i class="fa fa-caret-down"></i>
                    </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <?php
                        use Application\Infrastructure\DataTransferObject\SubmenuNavItem;
                        use Professionnal\Infrastructure\DataTransferObject\HeaderNavItem;
                    ?>
                    <ul class="nav navbar-nav">

                        <li class="visible-xs"><a href="<?= $this->url('application-home') ?>">Accès public</a></li>
                        
                        <?php if ($this->isAllowed('professionnal-dashboard')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::DASHBOARD) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-dashboard'); ?>">Tableau de bord</a></li>
                        <?php endif; ?>
                        
                        <?php if ($this->isAllowed('professionnal-booking')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::BOOKING) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-booking'); ?>">Mes rendez-vous</a></li>
                        <?php endif; ?>
                        
                        <?php if ($this->isAllowed('professionnal-discount/edit')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::DISCOUNT) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-discount/edit'); ?>">Promotions</a></li>
                        <?php endif; ?>

                        <?php if (
                            $this->isAllowed('professionnal-salon/create')
                            || $this->isAllowed('professionnal-salon/edit')
                            || $this->isAllowed('professionnal-job-service-template')
                            || $this->isAllowed('professionnal-salon/salon-invitation-list')
                            || $this->isAllowed('professionnal-salon/manage-images')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::SALON) ? ' active' : ''; ?>">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Salon <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">

                                    <?php if ($this->isAllowed('professionnal-salon/create')) : ?>
                                        <li><a href="<?= $this->url('professionnal-salon/create'); ?>">Créer</a></li>
                                    <?php endif; ?>

                                    <?php if ($this->isAllowed('professionnal-salon/salon-attachment-request-list')) : ?>
                                        <li><a href="<?= $this->url('professionnal-salon/salon-attachment-request-list'); ?>">Demandes de rattachement</a></li>
                                    <?php endif; ?>

                                    <?php if ($this->isAllowed('professionnal-job-service-template')) : ?>
                                        <li><a href="<?= $this->url('professionnal-job-service-template'); ?>">Liste des prestations modèles</a></li>
                                    <?php endif; ?>
                                        
                                    <?php if ($this->isAllowed('professionnal-salon/edit')) : ?>
                                        <li><a href="<?= $this->url('professionnal-salon/edit'); ?>">Informations</a></li>
                                    <?php endif; ?>

                                    <?php if ($this->isAllowed('professionnal-salon/manage-images')) : ?>
                                        <li><a href="<?= $this->url('professionnal-salon/manage-images'); ?>">Gérer les photos</a></li>
                                    <?php endif; ?>

                                </ul>
                            </li>
                        <?php endif; ?>

                        <?php if (
                            $this->isAllowed('professionnal-availabilities')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::AVAILABILITIES) ? ' active' : ''; ?>">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Planning <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php if ($this->isAllowed('professionnal-availabilities/edit')) : ?>
                                        <li>
                                            <a href="<?= $this->url('professionnal-availabilities/edit'); ?>">Planning hebdomadaire</a>
                                        </li>
                                    <?php endif; ?>

                                    <?php if ($this->isAllowed('professionnal-availabilities/exception-list')) : ?>
                                        <li>
                                            <a href="<?= $this->url('professionnal-availabilities/exception-list'); ?>">Absences/disponibilités</a>
                                        </li>
                                    <?php endif; ?>

                                </ul>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-job-service')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::JOB_SERVICE) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-job-service'); ?>">Prestations</a></li>
                        <?php endif; ?>

                        <?php if (
                            $this->isAllowed('professionnal-financial/list-transfer-request')
                            || $this->isAllowed('professionnal-financial/list-transaction')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::FINANCIAL) ? ' active' : ''; ?>">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Finances <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">

                                    <?php if ($this->isAllowed('professionnal-financial/list-transaction')) : ?>
                                        <li><a href="<?= $this->url('professionnal-financial/list-transaction'); ?>">Liste des transactions</a></li>
                                    <?php endif; ?>
                                    
                                    <?php if ($this->isAllowed('professionnal-financial/list-transfer-request')) : ?>
                                        <li><a href="<?= $this->url('professionnal-financial/list-transfer-request'); ?>">Liste des demandes de virement</a></li>
                                    <?php endif; ?>

                                </ul>
                            </li>
                        <?php endif; ?>

                    </ul>
                </div>
                <div id="account-navbar" class="collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($this->isAllowed('professionnal-profile-edit')) : ?>
                            <li>
                                <a href="<?= $this->url('professionnal-profile-edit'); ?>">
                                    <i class="fa fa-user"></i> Profil
                                </a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->isTakeOver === true) : ?>
                            <li><a href="<?= $this->url('administration-account/end-take-over'); ?>">Quitter la session</a></li>
                        <?php elseif ($this->isAllowed('application-logout')) : ?>
                            <li><a href="<?= $this->url('application-logout'); ?>"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        
        
        <div id="navbar-menu" class="navbar navbar-gestion navbar-default hidden-sm hidden-xs hidden-md">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($this->isAllowed('professionnal-dashboard')) : ?>
                        <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::DASHBOARD) ? ' active' : ''; ?>">
                            <a href="<?= $this->url('professionnal-dashboard'); ?>">Tableau de bord</a>
                        </li>
                        <?php endif; ?>
                        
                        <?php if ($this->isAllowed('professionnal-booking')) : ?>
                        <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::BOOKING) ? ' active' : ''; ?>">
                            <a href="<?= $this->url('professionnal-booking'); ?>">Mes rendez-vous</a>
                        </li>
                        <?php endif; ?>
                        
                        <?php if ($this->isAllowed('professionnal-discount/edit')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::DISCOUNT) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-discount/edit'); ?>">Promotions</a></li>
                        <?php endif; ?>
                            
                        <?php if (
                            $this->isAllowed('professionnal-salon/create')
                            || $this->isAllowed('professionnal-salon/edit')
                            || $this->isAllowed('professionnal-job-service-template')
                            || $this->isAllowed('professionnal-salon/salon-invitation-list')
                            || $this->isAllowed('professionnal-salon/manage-images')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::SALON) ? ' active' : ''; ?>">
                                <a href="#" data-target="#menu-salon">
                                    Salon <span class="caret"></span>
                                </a>
                            </li>
                        <?php endif; ?>
                            
                        <?php if (
                            $this->isAllowed('professionnal-availabilities')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::AVAILABILITIES) ? ' active' : ''; ?>">
                                <a href="#" data-target="#menu-planning">
                                    Planning <span class="caret"></span>
                                </a>
                            </li>
                        <?php endif; ?>
                            
                        <?php if ($this->isAllowed('professionnal-job-service')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::JOB_SERVICE) ? ' active' : ''; ?>"><a href="<?= $this->url('professionnal-job-service'); ?>">Prestations</a></li>
                        <?php endif; ?>
                            
                        <?php if (
                            $this->isAllowed('professionnal-financial/list-transfer-request')
                            || $this->isAllowed('professionnal-financial/list-transaction')
                        ) : ?>
                            <li class="dropdown <?= ($this->selectedHeaderNavItem === HeaderNavItem::FINANCIAL) ? ' active' : ''; ?>">
                                <a href="#" data-target="#menu-finances">
                                    Finances <span class="caret"></span>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle profil" data-toggle="dropdown">
                                <?php if($account->getAccountImageFilename() !== null): ?>
                                <img src="<?= $this->url('application-load-image', [
                                    'category' => 'account-image',
                                    'idImage' => $account->getAccountImageFilename(),
                                    'width' => '36',
                                    'height' => '36'
                                ]); ?>" width="36" class="img-circle" />
                                <?php else: ?>
                                <img src="/img/avatar.jpg" width="36" class="img-circle" />
                                <?php endif; ?>
                                <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/professionnel/modification-profil">
                                        <i class="fa fa-user"></i> Profil
                                    </a>
                                </li>

                                <li><a href="/administration/compte/quitter-prise-de-controle">Quitter la session</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                
            </div>
        </div>
        
        
        <nav id="submenu" class="nav nav-justified navbar-default hidden-sm hidden-xs hidden-md">
            <div class="container">
                <?php if (
                    $this->isAllowed('professionnal-salon/create')
                    || $this->isAllowed('professionnal-salon/edit')
                    || $this->isAllowed('professionnal-job-service-template')
                    || $this->isAllowed('professionnal-salon/salon-invitation-list')
                    || $this->isAllowed('professionnal-salon/manage-images')
                ) : ?>
                    <ul class="nav nav-justified <?= ($this->selectedHeaderNavItem === HeaderNavItem::SALON) ? '' : ' collapse'; ?>" id="menu-salon">
                        <?php if ($this->isAllowed('professionnal-salon/create')) : ?>
                        <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::SALON_CREATE) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-salon/create'); ?>">Créer</a></li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-salon/salon-attachment-request-list')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::ATTACHMENT_REQUEST_LIST) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-salon/salon-attachment-request-list'); ?>">Demandes de rattachement</a></li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-job-service-template')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::JOB_SERVICE_TEMPLATE_LIST) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-job-service-template'); ?>">Liste des prestations modèles</a></li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-salon/edit')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::SALON_INFORMATIONS) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-salon/edit'); ?>">Informations</a></li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-salon/manage-images')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::SALON_MANAGE_PICTURES) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-salon/manage-images'); ?>">Gérer les photos</a></li>
                        <?php endif; ?>
                    </ul>
                <?php endif; ?>

                <?php if (
                    $this->isAllowed('professionnal-availabilities')
                ) : ?>
                    <ul class="nav nav-justified <?= ($this->selectedHeaderNavItem === HeaderNavItem::AVAILABILITIES) ? '' : ' collapse'; ?>" id="menu-planning">
                        <?php if ($this->isAllowed('professionnal-availabilities/edit')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::AVAILABILITIES) ? 'active' : ''; ?>">
                                <a href="<?= $this->url('professionnal-availabilities/edit'); ?>">Planning hebdomadaire</a>
                            </li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-availabilities/exception-list')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::EXCEPTIONS) ? 'active' : ''; ?>">
                                <a href="<?= $this->url('professionnal-availabilities/exception-list'); ?>">Absences/disponibilités</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                <?php endif; ?>

                <?php if (
                    $this->isAllowed('professionnal-financial/list-transfer-request')
                    || $this->isAllowed('professionnal-financial/list-transaction')
                ) : ?>
                    <ul class="nav nav-justified <?= ($this->selectedHeaderNavItem === HeaderNavItem::FINANCIAL) ? '' : ' collapse'; ?>" id="menu-finances">
                        <?php if ($this->isAllowed('professionnal-financial/list-transaction')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::TRANSACTION_LIST) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-financial/list-transaction'); ?>">Liste des transactions</a></li>
                        <?php endif; ?>

                        <?php if ($this->isAllowed('professionnal-financial/list-transfer-request')) : ?>
                            <li class="<?= ($this->selectedSubmenuNavItem === SubmenuNavItem::TRANSFER_REQUEST_LIST) ? 'active' : ''; ?>"><a href="<?= $this->url('professionnal-financial/list-transfer-request'); ?>">Liste des demandes de virement</a></li>
                        <?php endif; ?>
                    </ul>
                <?php endif; ?>


            </div>
        </nav>
        

        <?php if ($this->isAllowed('professionnal-join-salon')): ?>
        <div class="alert alert-danger rejoindre-salon">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                    Afin de rejoindre un salon, vous devez vous munir de l'adresse e-mail de son gérant.
                    Celui-ci recevera une notification, et pourra ensuite accepter ou refuser votre demande.
                    </div>
                    <div class="col-md-3 text-right">
                        <a href="<?= $this->url('professionnal-join-salon'); ?>" class="btn btn-primary">Rejoindre un salon</a>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        
        <?php 
            if ($newUserBanner
                && $actualRoute !== 'professionnal-dashboard'
                && !$this->isAllowed('professionnal-join-salon')
            ): 
        ?>
        <div class="alert alert-danger rejoindre-salon">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <b>Vos prestations ne sont pas encore publiées.</b><br>
                        Prenez quelques minutes pour terminer votre inscription
                    </div>
                    <div class="col-md-3 text-right">
                        <a href="<?= $this->url('professionnal-dashboard'); ?>" class="btn btn-primary">Compléter votre inscription</a>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>

        <div class="container">
            <?= $this->displayFlashMessages('success'); ?>
            <?= $this->displayFlashMessages('info'); ?>
            <?= $this->displayFlashMessages('warning'); ?>
            <?= $this->displayFlashMessages('error'); ?>
            
            <?= $this->content; ?>
        </div>
        
        <script type="text/javascript">
            $(document).ready(function() {
                hairlov.navbar.init();
            });
        </script>
        
        <?= $this->inlineScript(); ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76454729-1', 'auto');
  ga('send', 'pageview');

</script>        
    </body>
</html>