<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="/img/favicon.png" />
        
        <?= $this->headTitle(), $this->headMeta(), $this->headLink(), $this->headScript(); ?>
        
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="header" class="header header-gestion">
            <div class="container">
                <div class="header-logo">
                    <a href="<?= $this->url('administration-account'); ?>" title="Retour au tableau de bord">
                        <span class="logo">Hairlov</span>
                        <span class="slogan">Coiffeurs privés</span>
                    </a>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-gestion navbar-default">
            <div class="container">
                <div class="navbar-header hidden-lg">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Afficher la navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?= $this->url('administration-account'); ?>" class="navbar-brand">Menu</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <?php use Administration\Infrastructure\DataTransferObject\HeaderNavItem; ?>
                    <ul class="nav navbar-nav">
                        
                        <?php if ($this->isAllowed('administration-account')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::ACCOUNT) ? ' active' : ''; ?>"><a href="<?= $this->url('administration-account'); ?>">Comptes</a></li>
                        <?php endif; ?>
                            
                            <?php if ($this->isAllowed('administration-salon')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::SALON) ? ' active' : ''; ?>"><a href="<?= $this->url('administration-salon'); ?>">Salons</a></li>
                        <?php endif; ?>
                        
                        <?php if ($this->isAllowed('administration-prospect')) : ?>
                            <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::PROSPECT) ? ' active' : ''; ?>"><a href="<?= $this->url('administration-prospect'); ?>">Prospects</a></li>
                        <?php endif; ?>
                                                
                        <?php if ($this->isAllowed('application-logout')) : ?>
                            <li><a href="<?= $this->url('application-logout'); ?>">Déconnexion</a></li>
                        <?php endif; ?>
                        
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?= $this->displayFlashMessages('success'); ?>
            <?= $this->displayFlashMessages('info'); ?>
            <?= $this->displayFlashMessages('warning'); ?>
            <?= $this->displayFlashMessages('error'); ?>
            
            <?= $this->content; ?>
        </div>
        
        <script type="text/javascript">
            $(document).ready(function() {
                hairlov.navbar.init();
            });
        </script>
        
        <?= $this->inlineScript(); ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76454729-1', 'auto');
  ga('send', 'pageview');

</script>        
    </body>
</html>