<?php $this->headTitle()->set('HAIRLOV.com : Trouver un coiffeur privé près de chez vous.'); ?>
<?php

use Backend\Infrastructure\DataTransferObject\ProfessionalSearchResult;

    // Chargement de l'API Google Maps
    $this->headScript()
        ->appendFile('https://maps.googleapis.com/maps/api/js?key='.$mapsApiConfig['applicationKey'].'&libraries=places');

    $this->professionalSearchForm
        ->setAttribute('method', 'get')
        ->setAttribute('class', 'form-search');

    $dateElement = $this->professionalSearchForm->get('date');
    $dateElement
        ->setAttribute('id', 'date')
        ->setAttribute('class', 'form-control datepicker-search')
        ->setAttribute('placeholder', 'Date')
    ;
    
    $dateHiddenElement = $this->professionalSearchForm->get('date_hidden');
    
    $minLikeElement = $this->professionalSearchForm->get('minLike');
    $minLikeElement
        ->setAttribute('id', 'min-like')
        ->setAttribute('class', 'form-control')
    ;

    $minRateElement = $this->professionalSearchForm->get('minRate');
    $minRateElement
        ->setAttribute('id', 'min-rate')
        ->setAttribute('class', 'form-control')
    ;

    $maxPriceElement = $this->professionalSearchForm->get('maxPrice');
    $maxPriceElement
        ->setAttribute('id', 'max-price')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Prix max')
    ;

    $jobSeviceTypeElement = $this->professionalSearchForm->get('idJobServiceType');
    $jobSeviceTypeElement
        ->setAttribute('id', 'job-service-type')
        ->setAttribute('class', 'form-control')
    ;

    $customerCharacteristicElement = $this->professionalSearchForm->get('idCustomerCharacteristic');
    $customerCharacteristicElement
        ->setAttribute('id', 'customer-characteristic')
        ->setAttribute('class', 'form-control')
    ;

    $professionalTypeElement = $this->professionalSearchForm->get('idAccountType');
    $professionalTypeElement
        ->setAttribute('id', 'account-type')
        ->setAttribute('class', 'form-control')
    ;
    
    $addressElement = $this->professionalSearchForm->get('address');
    $addressElement
        ->setAttribute('id', 'address')
        ->setAttribute('class', 'form-control js-address')
        ->setAttribute('placeholder', 'Ma localisation')
    ;

    $latitudeElement = $this->professionalSearchForm->get('latitude');
    $latitudeElement
        ->setAttribute('id', 'latitude')
        ->setAttribute('class', 'form-control js-latitude')
    ;

    $longitudeElement = $this->professionalSearchForm->get('longitude');
    $longitudeElement
        ->setAttribute('id', 'longitude')
        ->setAttribute('class', 'form-control js-longitude')
    ;
?>

<div class="container">
    <?= $this->form()->openTag($this->professionalSearchForm); ?>

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <?= $this->formText($addressElement); ?>
                    <?= $this->displayFormElementErrors($addressElement); ?>
                </div>
            </div>

            <?= $this->formHidden($latitudeElement); ?>
            <?= $this->formHidden($longitudeElement); ?>

            <div class="col-md-3">
                <div class="form-group <?= ($dateElement->getMessages()) ? ' has-error' : ''; ?>">
                    <?= $this->formText($dateElement); ?>
                    <?= $this->formHidden($dateHiddenElement); ?>
                    <?= $this->displayFormElementErrors($dateElement); ?>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group <?= ($minRateElement->getMessages()) ? ' has-error' : ''; ?>">
                     <?= $this->formSelect($minRateElement); ?>
                    <?= $this->displayFormElementErrors($minRateElement); ?>
                </div>
            </div>
            
            <div class="col-md-3">
                <?php foreach($professionalTypeElement->getValueOptions() as $key => $item): ?>
                    <?php $checked = (!is_array($professionalTypeElement->getValue()) || !in_array($key, $professionalTypeElement->getValue())) ? '' : ' checked="checked"'; ?>
                    <div class="checkbox-inline">
                        <label>
                            <input type="checkbox" name="idAccountType[]" value="<?= $key ?>"<?= $checked; ?>> <?= $item; ?>
                        </label>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 col-md-offset-9">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">
                        <i class="fa fa-check"></i>&nbsp;
                        Lancer la recherche
                    </button>
                </div>
            </div>

        </div>
    <?= $this->form()->closeTag($this->professionalSearchForm); ?>
    
    <h1 class="h2 title main margin-top-0">Les coiffeurs</h1>
    <div class="row">
        <div class="col-md-12">

                <?php if(isset($this->professionalList) && !$this->professionalList->isEmpty()): ?>

                    <div class="row">

                        <?php foreach($this->professionalList as $professional): ?>
                            <?php /* @var $professional ProfessionalSearchResult */ ?>

                            <div class="col-md-6">
                                <div class="coiffeur-list ">
                                    <?php if ($professional->isSalon) : ?>
                                        <span class="professional-location">En salon</span>
                                    <?php else : ?>
                                        <span class="professional-location">A domicile</span>
                                    <?php endif; ?>
                                    <?php 
                                        $professionalSlug = $this->slugify(
                                            $professional->accountName . ' a ' .
                                            $professional->accountLocation
                                        );
                                    ?>
                                    <div class="inner">
                                        <div class="coiffeur-header clearfix">
                                            <div class="coiffeur-title-container clearfix">
                                                <?php $professional->accountImageFilename = ($professional->accountImageFilename != null)?$professional->accountImageFilename:'avatar.jpg';  ?>
                                                <div class="avatar-container" style="background-image: url('<?= $this->url('application-load-image', [
                                                    'category' => 'account-image',
                                                    'idImage' => $professional->accountImageFilename,
                                                    'width' => 100,
                                                    'height' => 100
                                                ]) ?>') ">
                                                </div>
                                                <div class="coiffeur-nom-container va-middle">
                                                    <h1 class="h2 coiffeur-nom"><a href="<?= $this->url('application-professional', ['idProfessional' => $professional->accountId]) ?>-<?= $professionalSlug ?>"><?= $professional->accountName; ?></a></h1>

                                                    <?php if($professional->accountRate != null) : ?>
                                                    <?php $note = round($professional->accountRate) ?>
                                                        <small>(<?= $note ?>/5)</small>
                                                        <ul class="list-inline note-count">
                                                            <?php
                                                                foreach(range(1, 5) as $key):
                                                            ?>
                                                                <?php if($note >= $key): ?>
                                                                    <li class="active"><span><i class="fa fa-circle"></i></span></li>
                                                                <?php else: ?>
                                                                    <li><span><i class="fa fa-circle-thin"></i></span></li>
                                                                <?php endif; ?>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php else: ?>
                                                        <span class="badge">Aucune évaluation</span>
                                                    <?php endif; ?>

                                                </div>
                                                <div class="pull-right">
                                                    <div class="coiffeur-lov-height">
                                                        <button class="js-like-switch coiffeur-lov va-middle" data-professional="<?= $professional->accountId; ?>" data-toggle="tooltip" data-placement="bottom" title="Lover">
                                                            <span><?= $professional->accountLike ?></span>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="coiffeur-prestation">

                                            <?php $jobServiceImageFilenameList = explode(',', $professional->jobServiceImageFilenameList); ?>
                                            <?php if (count($jobServiceImageFilenameList) > 0) : ?>
                                                <div class="row">
                                                    <?php for ($i = 0; $i < count($jobServiceImageFilenameList) && $i < 4; $i++) : ?>
                                                        <div class="col-md-3 col-sm-3 col-xs-6">
                                                            <div class="book-photo overflow-image xs image-cover" style="background-image: url('<?= $this->url('application-load-image', [
                                                                'category' => 'job-service-image',
                                                                'idImage' => $jobServiceImageFilenameList[$i],
                                                                'width' => 105,
                                                                'height' => 120
                                                            ]) ?>')">
                                                            </div>
                                                        </div>
                                                    <?php endfor; ?>
                                                </div>
                                            <?php endif; ?>

                                            <div class="text-right">
                                                <a href="<?= $this->url('application-professional', ['idProfessional' => $professional->accountId]) ?>-<?= $professionalSlug ?>" class="btn btn-primary btn-block">Voir le profil</a>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        <?php endforeach; ?>

                    </div>

                <?php else : ?>

                <div class="alert alert-info">Nous n'avons trouvé aucune coiffeur correspondant à vos critères</div>

                <?php endif; ?>

        </div>
    </div>

</div>

<?php if(isset($logInForm)): ?>
    <?= $this->partial('partials/login'); ?>
<?php endif; ?>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function () {
    hairlov.application.jobService.search.init();
    hairlov.application.professional.professionalPage.init();
    <?php if (isset($facebookApi)) : ?>
    hairlov.application.index.customerLandingPage().init(<?= $facebookApi['applicationId'] ?>);
    <?php endif; ?>
});
<?php $this->inlineScript()->captureEnd(); ?>