<?php $this->headTitle()->set('HAIRLOV.com : Contactez-nous'); ?>
<div class="container-fluid image-cover mod-map" style="height: 30vh"></div>

<div class="container">
    <h1 class="h2 title main">Contactez-nous</h1>
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <div class="box-title-container">
                    <div class="box-title">Par téléphone</div>
                </div>
                <div class="box-content">Contactez Martin au <b>06.10.56.29.77</b></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box">
                <div class="box-title-container">
                    <div class="box-title">
                        <div>Par mail</div>
                    </div>
                </div>
                <div class="box-content">Contactez Martin par mail <a href="mailto:mtkaptouom@yahoo.fr">mtkaptouom@yahoo.fr</a></div>
            </div>
        </div>
    </div>
</div>

