<div class="box">
    <div class="box-title-container clearfix">
        <div class="box-title">Supprimer l'exception</div>
    </div>
    <div class="box-content pb-5">
        <div class="alert alert-danger">
            Vous êtes sur le point de supprimer une exception.<br>
            Attention, cette action est irréversible.
        </div>
            <div class="form-group clearfix">
                <div class="col-sm-12">
                    <a href="<?= $this->url('professionnal-availabilities/exception-list'); ?>" class="btn btn-default pull-left">
                        <i class="fa fa-close"></i>&nbsp;
                        Annuler
                    </a>
                    <form method="post">
                        <button type="submit" class="btn btn-primary pull-right">
                            <i class="fa fa-trash"></i>&nbsp;
                            Supprimer
                        </button>
                    </form>
                </div>
            </div>
    </div>
</div>