<?php
    $this->editAvailabilitiesForm
            ->setAttribute('class', 'form-horizontal')
            ->prepare();

    $mondayElement = $this->editAvailabilitiesForm->get('monday');
    $mondayElement
        ->setAttribute('id', 'availabilities-monday')
        ->setAttribute('class', 'form-control')
    ;

    $tuesdayElement = $this->editAvailabilitiesForm->get('tuesday');
    $tuesdayElement
        ->setAttribute('id', 'availabilities-tuesday')
        ->setAttribute('class', 'form-control')
    ;
    
    $wednesdayElement = $this->editAvailabilitiesForm->get('wednesday');
    $wednesdayElement
        ->setAttribute('id', 'availabilities-wednesday')
        ->setAttribute('class', 'form-control')
    ;
    
    $thursdayElement = $this->editAvailabilitiesForm->get('thursday');
    $thursdayElement
        ->setAttribute('id', 'availabilities-thursday')
        ->setAttribute('class', 'form-control')
    ;
    
    $fridayElement = $this->editAvailabilitiesForm->get('friday');
    $fridayElement
        ->setAttribute('id', 'availabilities-friday')
        ->setAttribute('class', 'form-control')
    ;
    
    $saturdayElement = $this->editAvailabilitiesForm->get('saturday');
    $saturdayElement
        ->setAttribute('id', 'availabilities-saturday')
        ->setAttribute('class', 'form-control')
    ;
    
    $sundayElement = $this->editAvailabilitiesForm->get('sunday');
    $sundayElement
        ->setAttribute('id', 'availabilities-sunday')
        ->setAttribute('class', 'form-control')
    ;

?>

<?= $this->form()->openTag($this->editAvailabilitiesForm); ?>
        
        <?php if (isset($this->editAvailabilitiesError) === true) {
            echo $this->displayAlert($this->editAvailabilitiesError, DisplayAlert::ERROR);
        } ?>

        <div class="box">
            <div class="box-title-container clearfix">
                <div class="box-title">Planning hebdomadaire</div>
            </div>
            <div class="box-content clearfix">
                <div class="text-muted mg-b">
                    <p><b class="underline">Attention :</b> Les plages horaires ci-dessous sont celles durant lesquelles vous êtes obligés d'accepter les prestations venant de Hairlov.</p>
                    <div>
                        <b class="underline">Comment faire:</b>
                        <ol class="no-mg">
                            <li>Cliquez sur « ajouter une plage horaire » le jour de votre choix ou tous le jours.</li>
                            <li>Remplissez les heures disponibles le matin et l'après-midi.</li>
                        </ol>
                        <span>Ce planning se répète automatiquement chaque semaines</span>
                    </div>
                </div>
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="monday" data-target="#<?= $mondayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Lundi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($mondayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                            
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="tuesday" data-target="#<?= $tuesdayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Mardi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($tuesdayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                                        
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                                        
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                                        
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                                        
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="wednesday" data-target="#<?= $wednesdayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Mercredi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($wednesdayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                            
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="thursday" data-target="#<?= $thursdayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Jeudi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($thursdayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                        
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                        
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                        
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                        
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="friday" data-target="#<?= $fridayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Vendredi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($fridayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                            
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="saturday" data-target="#<?= $saturdayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Samedi</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($saturdayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                            
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box">
                    <div class="box-title-container clearfix">
                        <div class="box-tools pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm js-add-template" data-day="sunday" data-target="#<?= $sundayElement->getAttribute('id'); ?>">
                                    <i class="fa fa-plus-circle"></i>&nbsp;
                                    Ajouter une plage horaire
                                </button>
                            </div>
                        </div>
                        <div class="box-title">Dimanche</div>
                    </div>
                    <div class="box-content pb-5">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8" data-insert>
                                <?php foreach ($sundayElement as $items) : ?>
                                    <div class="js-availability">
                                        <div class="row">
                                            <?php
                                                $start = $items->get('start');
                                                $start->setAttribute('class', 'form-control');
                                                $end = $items->get('end');
                                                $end->setAttribute('class', 'form-control');
                                            ?>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">De</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($start); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-xs-12 col-sm-5 col-custom">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">à</label> 
                                                    <div class="col-md-10"><?php echo $this->formSelect($end); ?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-sm-2 hidden-xs col-custom">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="Supprimer">
                                                    <i class="fa fa-remove"></i>
                                                </button>
                                            </div>
                                            
                                            <div class="col-xs-12 visible-xs col-custom text-center">
                                                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                                                    <i class="fa fa-remove"></i> Supprimer cette plage
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary pull-right">
                    <i class="fa fa-check"></i> Enregistrer le planning
                </button>
            </div>
        </div>

<span class="template" data-template='
<div class="js-availability">
    <div class="row">
        <div class="col-xs-12 col-sm-5 col-custom">
            <div class="form-group">
                <label class="col-md-2 control-label">De</label> 
                <div class="col-md-10">
                    <select name="__day__[__index__][start]" class="form-control">
                        <option value="06:00">06h00</option>
                        <option value="06:15">06h15</option>
                        <option value="06:30">06h30</option>
                        <option value="06:45">06h45</option>
                        <option value="07:00">07h00</option>
                        <option value="07:15">07h15</option>
                        <option value="07:30">07h30</option>
                        <option value="07:45">07h45</option>
                        <option value="08:00">08h00</option>
                        <option value="08:15">08h15</option>
                        <option value="08:30">08h30</option>
                        <option value="08:45">08h45</option>
                        <option value="09:00" selected="selected">09h00</option>
                        <option value="09:15">09h15</option>
                        <option value="09:30">09h30</option>
                        <option value="09:45">09h45</option>
                        <option value="10:00">10h00</option>
                        <option value="10:15">10h15</option>
                        <option value="10:30">10h30</option>
                        <option value="10:45">10h45</option>
                        <option value="11:00">11h00</option>
                        <option value="11:15">11h15</option>
                        <option value="11:30">11h30</option>
                        <option value="11:45">11h45</option>
                        <option value="12:00">12h00</option>
                        <option value="12:15">12h15</option>
                        <option value="12:30">12h30</option>
                        <option value="12:45">12h45</option>
                        <option value="13:00">13h00</option>
                        <option value="13:15">13h15</option>
                        <option value="13:30">13h30</option>
                        <option value="13:45">13h45</option>
                        <option value="14:00">14h00</option>
                        <option value="14:15">14h15</option>
                        <option value="14:30">14h30</option>
                        <option value="14:45">14h45</option>
                        <option value="15:00">15h00</option>
                        <option value="15:15">15h15</option>
                        <option value="15:30">15h30</option>
                        <option value="15:45">15h45</option>
                        <option value="16:00">16h00</option>
                        <option value="16:15">16h15</option>
                        <option value="16:30">16h30</option>
                        <option value="16:45">16h45</option>
                        <option value="17:00">17h00</option>
                        <option value="17:15">17h15</option>
                        <option value="17:30">17h30</option>
                        <option value="17:45">17h45</option>
                        <option value="18:00">18h00</option>
                        <option value="18:15">18h15</option>
                        <option value="18:30">18h30</option>
                        <option value="18:45">18h45</option>
                        <option value="19:00">19h00</option>
                        <option value="19:15">19h15</option>
                        <option value="19:30">19h30</option>
                        <option value="19:45">19h45</option>
                        <option value="20:00">20h00</option>
                        <option value="20:15">20h15</option>
                        <option value="20:30">20h30</option>
                        <option value="20:45">20h45</option>
                        <option value="21:00">21h00</option>
                        <option value="21:15">21h15</option>
                        <option value="21:30">21h30</option>
                        <option value="21:45">21h45</option>
                        <option value="22:00">22h00</option>
                        <option value="22:15">22h15</option>
                        <option value="22:30">22h30</option>
                        <option value="22:45">22h45</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-5 col-custom">
            <div class="form-group">
                <label class="col-md-2 control-label">à</label>
                <div class="col-md-10">
                    <select name="__day__[__index__][end]" class="form-control">
                        <option value="06:00">06h00</option>
                            <option value="06:15">06h15</option>
                            <option value="06:30">06h30</option>
                            <option value="06:45">06h45</option>
                            <option value="07:00">07h00</option>
                            <option value="07:15">07h15</option>
                            <option value="07:30">07h30</option>
                            <option value="07:45">07h45</option>
                            <option value="08:00">08h00</option>
                            <option value="08:15">08h15</option>
                            <option value="08:30">08h30</option>
                            <option value="08:45">08h45</option>
                            <option value="09:00">09h00</option>
                            <option value="09:15">09h15</option>
                            <option value="09:30">09h30</option>
                            <option value="09:45">09h45</option>
                            <option value="10:00">10h00</option>
                            <option value="10:15">10h15</option>
                            <option value="10:30">10h30</option>
                            <option value="10:45">10h45</option>
                            <option value="11:00">11h00</option>
                            <option value="11:15">11h15</option>
                            <option value="11:30">11h30</option>
                            <option value="11:45">11h45</option>
                            <option value="12:00">12h00</option>
                            <option value="12:15">12h15</option>
                            <option value="12:30">12h30</option>
                            <option value="12:45">12h45</option>
                            <option value="13:00">13h00</option>
                            <option value="13:15">13h15</option>
                            <option value="13:30">13h30</option>
                            <option value="13:45">13h45</option>
                            <option value="14:00">14h00</option>
                            <option value="14:15">14h15</option>
                            <option value="14:30">14h30</option>
                            <option value="14:45">14h45</option>
                            <option value="15:00">15h00</option>
                            <option value="15:15">15h15</option>
                            <option value="15:30">15h30</option>
                            <option value="15:45">15h45</option>
                            <option value="16:00">16h00</option>
                            <option value="16:15">16h15</option>
                            <option value="16:30">16h30</option>
                            <option value="16:45">16h45</option>
                            <option value="17:00">17h00</option>
                            <option value="17:15">17h15</option>
                            <option value="17:30">17h30</option>
                            <option value="17:45">17h45</option>
                            <option value="18:00">18h00</option>
                            <option value="18:15">18h15</option>
                            <option value="18:30">18h30</option>
                            <option value="18:45">18h45</option>
                            <option value="19:00" selected="selected">19h00</option>
                            <option value="19:15">19h15</option>
                            <option value="19:30">19h30</option>
                            <option value="19:45">19h45</option>
                            <option value="20:00">20h00</option>
                            <option value="20:15">20h15</option>
                            <option value="20:30">20h30</option>
                            <option value="20:45">20h45</option>
                            <option value="21:00">21h00</option>
                            <option value="21:15">21h15</option>
                            <option value="21:30">21h30</option>
                            <option value="21:45">21h45</option>
                            <option value="22:00">22h00</option>
                            <option value="22:15">22h15</option>
                            <option value="22:30">22h30</option>
                            <option value="22:45">22h45</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 hidden-xs col-custom">
                <button type="button" class="btn btn-dark border-transparent js-remove-template" data-toggle="tooltip" data-placement="right" title="" data-original-title="Supprimer">
                    <i class="fa fa-remove"></i>
                </button>
            </div>
            <div class="col-xs-12 visible-xs col-custom text-center">
                <button type="button" class="btn btn-dark border-transparent js-remove-template">
                    <i class="fa fa-remove"></i> Supprimer cette plage
                </button>
            </div>
        </div>
    </div>
</div>
'></span>
<?= $this->form()->closeTag($this->editAvailabilitiesForm); ?>

<script>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    $('.js-add-template').on('click', function() {
        var $button = $(this);
        var brotherFieldsets = $(this).closest('.box').find('.box-content .js-availability');
        // Récupération du template des fieldsets pour les horaires de la journée
        var fieldsetTemplate = $(".template").data('template');
        // Récupération du nombre de champs courant
        var currentCount = brotherFieldsets.length;

        // Mise à jour de l'id du fieldset
        fieldsetTemplate = fieldsetTemplate.replace(/__index__/g, currentCount);
        fieldsetTemplate = fieldsetTemplate.replace(/__day__/g, $button.data('day'));
        $button.closest('.box').find('[data-insert]').append(fieldsetTemplate);
        
        return false;
    });
    
    $('body').on('click', '.js-remove-template', function() {
        var $button = $(this);
        
        // Suppression du parent
        $button.parent().parent().remove();
        
        return false;
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
</script>