<!DOCTYPE html>

<?php use Application\Infrastructure\DataTransferObject\HeaderNavItem; ?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="/img/favicon.png" />

        <?= $this->headTitle(), $this->headMeta(), $this->headLink(), $this->headScript(); ?>

        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body<?= ($this->landingPage == 'professionnal') ? ' class="landing-professional"' : ''; ?><?= ($this->landingPage == 'customer') ? ' class="landing-customer"' : ''; ?>>
        <?php if ($this->isTakeOver === true) : ?>
        <div class="text-center" style="font-size: 12px;background: #000;color: #fff">
            En cours de prise de contrôle de
            <b>"<?php echo $account->getFirstname().' '.$account->getLastname()?>"</b>
            <a href="<?= $this->url('administration-account/end-take-over'); ?>">Quitter la session</a>
        </div>
        <?php endif;?>
        <?php if (!$this->hideHeader): ?>
            <div id="header" class="header">
                <div class="container" style="position: relative;">
                    <div class="header-logo">
                        <a href="<?= $this->url('application-home'); ?>" title="Retour au tableau de bord">
                            <span class="logo">Hairlov</span>
                            <span class="slogan">Coiffeurs privés</span>
                        </a>
                    </div>
                    <?php if($this->isAllowed('professionnal-dashboard')) : ?>
                    <a href="<?= $this->url('professionnal-dashboard') ?>" class="btn btn-default margin-top-24 hidden-xs" style="position: absolute; right: 0">Accès professionnel</a>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($isLoggedIn): ?>
                <nav class="navbar navbar-default">
                    <div class="container">
                        <div class="navbar-header hidden-lg">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                <span class="sr-only">Afficher la navigation</span>
                                <div class="pull-left menu-text">MENU</div>
                                <div class="pull-right">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </div>
                            </button>
                            <button type="button" class="btn btn-link navbar-button collapsed visible-xs" data-toggle="collapse" data-target="#account-navbar" aria-expanded="false" aria-controls="navbar">
                                <?php if($account->getAccountImageFilename() !== null): ?>
                                <img src="<?= $this->url('application-load-image', [
                                    'category' => 'account-image',
                                    'idImage' => $account->getAccountImageFilename(),
                                    'width' => '36',
                                    'height' => '36'
                                ]); ?>" width="36" class="img-circle" />
                                <?php else: ?>
                                <img src="/img/avatar.jpg" width="36" class="img-circle" />
                                <?php endif; ?>
                                <i class="fa fa-caret-down"></i>
                            </button>
                        </div>
                        <div id="navbar" class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li class="dropdown hidden-xs">
                                    <a href="#" class="profil dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                                        <?php if ($account->getAccountImageFilename() !== null) : ?>
                                            <img src="<?= $this->url('application-load-image', [
                                                'category' => 'account-image',
                                                'idImage' => $account->getAccountImageFilename(),
                                                'width' => '36',
                                                'height' => '36'
                                            ]); ?>" width="36" class="img-circle" />
                                        <?php else : ?>
                                            <img src="http://www.gravatar.com/avatar/<?= md5($this->account->getEmail())?>?d=<?= urlencode($this->urlDomain.'img/avatar.jpg'); ?>" class="img-circle">
                                        <?php endif; ?>
                                        <i class="fa fa-caret-down"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= $this->url('application-liked-professional-list') ?>"><i class="fa fa-heart"></i> Mes lovs</a></li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="<?= $this->url('application-booking-list') ?>"><i class="fa fa-ticket"></i> Mes réservations</a></li>
                                        <li role="separator" class="divider"></li>
                                        <?php if ($this->isTakeOver === true) : ?>
                                            <li><a href="<?= $this->url('administration-account/end-take-over'); ?>"><i class="fa fa-sign-out"></i> Quitter la session</a></li>
                                        <?php elseif ($this->isAllowed('application-logout')) : ?>
                                            <li><a href="<?= $this->url('application-logout'); ?>"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </li>
                                <?php if($this->isAllowed('professionnal-dashboard')) : ?>
                                <li class="visible-xs"><a href="<?= $this->url('professionnal-dashboard') ?>">Accès professionnel</a></li>
                                <?php endif; ?>
                                <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::DASHBOARD) ? ' active' : ''; ?>"><a href="<?= $this->url('application-home'); ?>">Tendances</a></li>
                                <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::SEARCH_JOB_SERVICE) ? ' active' : ''; ?>"><a href="<?= $this->url('application-search-job-service') ?>">Rechercher une prestation</a></li>
                                <li class="<?= ($this->selectedHeaderNavItem === HeaderNavItem::SEARCH_PROFESSIONAL) ? ' active' : ''; ?>"><a href="<?= $this->url('application-search-professional'); ?>">Rechercher un coiffeur</a></li>
                            </ul>

                        </div>
                        <div id="account-navbar" class="collapse hidden-lg hidden-md hidden-sm">
                            
                            <ul class="nav navbar-nav">
                                <li><a href="<?= $this->url('application-liked-professional-list') ?>"><i class="fa fa-heart"></i> Mes lovs</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="<?= $this->url('application-booking-list') ?>"><i class="fa fa-ticket"></i> Mes réservations</a></li>
                                <li role="separator" class="divider"></li>
                                <?php if ($this->isTakeOver === true) : ?>
                                    <li><a href="<?= $this->url('administration-account/end-take-over'); ?>"><i class="fa fa-sign-out"></i> Quitter la session</a></li>
                                <?php elseif ($this->isAllowed('application-logout')) : ?>
                                    <li><a href="<?= $this->url('application-logout'); ?>"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                                <?php endif; ?>
                            </ul>

                        </div>
                    </div>
                </nav>
            <?php endif; ?>
        <?php endif; ?>
        
        <?php if (!$this->hideHeader): ?>
        
            <?php
                if (
                    $this->flashMessenger()->getPluginFlashMessenger()->hasSuccessMessages() ||
                    $this->flashMessenger()->getPluginFlashMessenger()->hasInfoMessages() ||
                    $this->flashMessenger()->getPluginFlashMessenger()->hasWarningMessages() ||
                    $this->flashMessenger()->getPluginFlashMessenger()->hasErrorMessages()
                ):
                $flashMessenger = $this->flashMessenger()
                    ->setMessageCloseString('</div>')
                    ->setMessageOpenFormat('<div %s><button type="button" class="close" data-dismiss="alert"><i class="fa fa-close"></i></button>')
                    ->setMessageSeparatorString('<br>');
                ?>

                <div class="container">
                    <?= $flashMessenger->render('success', ['alert', 'alert-success']); ?>
                    <?= $flashMessenger->render('info', ['alert', 'alert-info']); ?>
                    <?= $flashMessenger->render('warning', ['alert', 'alert-warning']); ?>
                    <?= $flashMessenger->render('error', ['alert', 'alert-danger']); ?>

                </div>

            <?php endif; ?>
        
        <?php endif; ?>

        <?= $this->content; ?>
        
        
        <?php if (!$this->hideFooter): ?>
        <div class="footer-main sticky">
            <div class="container">
                <ul class="list-inline pull-right">
                    <li><a href="<?= $this->url('application-contact'); ?>">Contact</a></li>
                    <li><a href="<?= $this->url('application-legal'); ?>">CGU / Légal</a></li>
                    <li><a href="<?= $this->url('application-search-job-service'); ?>">Prestations</a></li>
                    <li><a href="<?= $this->url('application-search-professional'); ?>">Coiffeurs</a></li>
                </ul>
            </div>
        </div>
        <?php endif; ?>
        
        <?php if (!$this->landingPage == 'customer'): ?>
        <script type="text/javascript">
            $(document).ready(function () {
                hairlov.application.init();
            });
        </script>
        <?php endif; ?>
        <?= $this->inlineScript(); ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76454729-1', 'auto');
  ga('send', 'pageview');

</script>
    </body>
</html>