<?php
/**
 * @package hairlov.fr
 * @author contact@wixiweb.fr
 */

return [
    'service_manager' => [
        'factories' => [
            'Backend\Service\Account' => 'Backend\Service\Factory\AccountServiceFactory',
            'Backend\Mapper\Account' => 'Backend\Mapper\Factory\AccountMapperFactory',
            'Backend\Service\AccountType' => 'Backend\Service\Factory\AccountTypeServiceFactory',
            'Backend\Mapper\AccountType' => 'Backend\Mapper\Factory\AccountTypeMapperFactory',
            'Backend\Service\AttachmentRequest' => 'Backend\Service\Factory\AttachmentRequestServiceFactory',
            'Backend\Mapper\AttachmentRequest' => 'Backend\Mapper\Factory\AttachmentRequestMapperFactory',
            'Backend\Service\Availability' => 'Backend\Service\Factory\AvailabilityServiceFactory',
            'Backend\Mapper\Availability' => 'Backend\Mapper\Factory\AvailabilityMapperFactory',
            'Backend\Service\Booking' => 'Backend\Service\Factory\BookingServiceFactory',
            'Backend\Mapper\Booking' => 'Backend\Mapper\Factory\BookingMapperFactory',
            'Backend\Service\BookingComment' => 'Backend\Service\Factory\BookingCommentServiceFactory',
            'Backend\Mapper\BookingComment' => 'Backend\Mapper\Factory\BookingCommentMapperFactory',
            'Backend\Service\CustomerCharacteristic' => 'Backend\Service\Factory\CustomerCharacteristicServiceFactory',
            'Backend\Mapper\CustomerCharacteristic' => 'Backend\Mapper\Factory\CustomerCharacteristicMapperFactory',
            'Backend\Service\Discount' => 'Backend\Service\Factory\DiscountServiceFactory',
            'Backend\Mapper\Discount' => 'Backend\Mapper\Factory\DiscountMapperFactory',
            'Backend\Service\FacebookAccount' => 'Backend\Service\Factory\FacebookAccountServiceFactory',
            'Backend\Mapper\FacebookAccount' => 'Backend\Mapper\Factory\FacebookAccountMapperFactory',
            'Backend\Service\FashionImage' => 'Backend\Service\Factory\FashionImageServiceFactory',
            'Backend\Mapper\FashionImage' => 'Backend\Mapper\Factory\FashionImageMapperFactory',
            'Backend\Service\Invoice' => 'Backend\Service\Factory\InvoiceServiceFactory',
            'Backend\Mapper\Invoice' => 'Backend\Mapper\Factory\InvoiceMapperFactory',
            'Backend\Service\JobService' => 'Backend\Service\Factory\JobServiceServiceFactory',
            'Backend\Mapper\JobService' => 'Backend\Mapper\Factory\JobServiceMapperFactory',
            'Backend\Service\JobServiceImage' => 'Backend\Service\Factory\JobServiceImageServiceFactory',
            'Backend\Mapper\JobServiceImage' => 'Backend\Mapper\Factory\JobServiceImageMapperFactory',
            'Backend\Service\JobServiceTemplate' => 'Backend\Service\Factory\JobServiceTemplateServiceFactory',
            'Backend\Mapper\JobServiceTemplate' => 'Backend\Mapper\Factory\JobServiceTemplateMapperFactory',
            'Backend\Service\JobServiceType' => 'Backend\Service\Factory\JobServiceTypeServiceFactory',
            'Backend\Mapper\JobServiceType' => 'Backend\Mapper\Factory\JobServiceTypeMapperFactory',
            'Backend\Service\Newsletter' => 'Backend\Service\Factory\NewsletterServiceFactory',
            'Backend\Mapper\Newsletter' => 'Backend\Mapper\Factory\NewsletterMapperFactory',
            'Backend\Service\Payment' => 'Backend\Service\Factory\PaymentServiceFactory',
            'Backend\Mapper\Payment' => 'Backend\Mapper\Factory\PaymentMapperFactory',
            'Backend\Service\Permission' => 'Backend\Service\Factory\PermissionServiceFactory',
            'Backend\Mapper\Permission' => 'Backend\Mapper\Factory\PermissionMapperFactory',
            'Backend\Service\Prospect' => 'Backend\Service\Factory\ProspectServiceFactory',
            'Backend\Mapper\Prospect' => 'Backend\Mapper\Factory\ProspectMapperFactory',
            'Backend\Service\Referral' => 'Backend\Service\Factory\ReferralServiceFactory',
            'Backend\Mapper\Referral' => 'Backend\Mapper\Factory\ReferralMapperFactory',
            'Backend\Service\Salon' => 'Backend\Service\Factory\SalonServiceFactory',
            'Backend\Mapper\Salon' => 'Backend\Mapper\Factory\SalonMapperFactory',
            'Backend\Service\SalonConfigurator' => 'Backend\Service\Factory\SalonConfiguratorServiceFactory',
            'Backend\Mapper\SalonConfigurator' => 'Backend\Mapper\Factory\SalonConfiguratorMapperFactory',
            'Backend\Service\SalonImage' => 'Backend\Service\Factory\SalonImageServiceFactory',
            'Backend\Mapper\SalonImage' => 'Backend\Mapper\Factory\SalonImageMapperFactory',
            'Backend\Mapper\Search' => 'Backend\Mapper\Factory\SearchMapperFactory',
            'Backend\Service\Transaction' => 'Backend\Service\Factory\TransactionServiceFactory',
            'Backend\Mapper\Transaction' => 'Backend\Mapper\Factory\TransactionMapperFactory',
            'Backend\Service\TransferRequest' => 'Backend\Service\Factory\TransferRequestServiceFactory',
            'Backend\Mapper\TransferRequest' => 'Backend\Mapper\Factory\TransferRequestMapperFactory',
            'Backend\Service\WeekTemplate' => 'Backend\Service\Factory\WeekTemplateServiceFactory',
            'Backend\Mapper\WeekTemplate' => 'Backend\Mapper\Factory\WeekTemplateMapperFactory',
            'Backend\Infrastructure\TransactionManager' => 'Backend\Infrastructure\Factory\TransactionManagerFactory',
        ]
    ],
];
