<div class="container">
    
<?php
    use Backend\Infrastructure\DataTransferObject\CompleteProfessional;
?>
    <?= $this->partial('partials/header', ['activeTab' => 'professional', 'salon' => $salon, 'salonImage' => $salonImage]); ?>
    
    <div class="row">
        <?php foreach ($employees as $employee) : ?>
            <?php
                $professionalSlug = $this->slugify(
                    $employee->firstName . ' ' . 
                    $employee->lastName . ' a ' .
                    $salon->getCity()
                );
            ?>
            <?php /* @var $employee CompleteProfessional */ ?>
            <div class="col-md-6">
                <div class="coiffeur-list">
                    <div class="inner">
                        <div class="coiffeur-header clearfix">
                            <div class="coiffeur-title-container clearfix">
                                <div class="avatar-container" style="background-image: url('<?= $this->url('application-load-image', [
                                    'category' => 'account-image',
                                    'idImage' => $employee->accountImageFilename ?: 'avatar.jpg',
                                    'width' => '100',
                                    'height' => '100'
                                ]) ?>') "></div>
                                <div class="coiffeur-nom-container va-middle">
                                    <h1 class="h2 coiffeur-nom"><a href="<?= $this->url('application-professional', ['idProfessional' => $employee->idProfessional]) ?>-<?= $professionalSlug ?>"><?= $employee->firstName ?> <?= $employee->lastName ?></a></h1>
                                    <?php if($employee->rate != null) : ?>
                                        <?php $note = round($employee->rate) ?>
                                        <small>(<?= $note ?>/5)</small>
                                        <ul class="list-inline note-count">
                                            <?php
                                                foreach(range(1, 5) as $key):
                                            ?>
                                                <?php if($note >= $key): ?>
                                                    <li class="active"><span><i class="fa fa-circle"></i></span></li>
                                                <?php else: ?>
                                                    <li><span><i class="fa fa-circle-thin"></i></span></li>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php else: ?>
                                        <span class="badge">Aucune évaluation</span>
                                    <?php endif; ?>
                                </div>
                                <div class="pull-right">
                                    <div class="coiffeur-lov-height">
                                        <button class="js-like-switch coiffeur-lov va-middle" data-professional="<?= $employee->idProfessional; ?>" data-toggle="tooltip" data-placement="bottom" title="Lover">
                                            <span><?= $employee->like ?></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="coiffeur-prestation">
                            <div class="row">
                                <?php $jobServiceImages = explode(',', $employee->jobServiceImageFilenameList) ?>
                                
                                <?php for ($i = 0; $i < count($jobServiceImages) && $i < 4; $i++) : ?>
                                    <div class="col-md-3 col-sm-3 col-xs-3">
                                        <div class="book-photo overflow-image xs image-cover" style="background-image: url('<?= $this->url('application-load-image', [
                                            'category' => 'job-service-image',
                                            'idImage' => $jobServiceImages[$i],
                                            'width' => 105,
                                            'height' => 120
                                        ]) ?>')">
                                        </div>
                                    </div>
                                <?php endfor; ?>
                            </div>

                            <div class="text-right">
                                <a href="<?= $this->url('application-professional', ['idProfessional' => $employee->idProfessional]) ?>-<?= $professionalSlug ?>" class="btn btn-primary btn-block">Réserver</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    
</div>
<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function () {
    hairlov.application.professional.professionalPage.init();
});
<?php $this->inlineScript()->captureEnd(); ?>