<div class="container">

    <?php 
        if ($this->futureBookingCollection->count() > 0
            || $this->pastBookingCollection->count() > 0
        ) : 
    ?>
        <div class="box">
            <div class="box-title-container clearfix">
                <div class="box-title">Réservations à venir</div>
            </div>
            <?php if ($this->futureBookingCollection->count() > 0) : ?>
                <div class="box-content padding-bottom-5">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nom de la prestation</th>
                                    <th>Date de début</th>
                                    <th>Durée</th>
                                    <th>Prix</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->futureBookingCollection as $booking) : ?>
                                    <?php /* @var $booking Backend\Entity\Booking */ ?>
                                    <tr>
                                        <td>
                                            <?= $booking->getJobServiceName() ?>
                                        </td>
                                        <td>
                                            <?php $date = new DateTime($booking->getStart()) ?>
                                            Le <b><?= $date->format('d/m/Y') ?></b> à <b><?= $date->format('H') ?>h<?= $date->format('i') ?></b>
                                        </td>
                                        <td>
                                            <?= $booking->getDuration() ?> minutes
                                        </td>
                                        <td>
                                            <?= $booking->getJobServicePrice() ?>€
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php else : ?>
                <div class="box-content padding-bottom-5">
                    <div class="alert alert-info">
                        Vous n'avez aucune réservation à venir.
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($this->pastBookingCollection->count() > 0) : ?>
            <div class="box">
                <div class="box-title-container clearfix">
                    <div class="box-title">Réservations passées</div>
                </div>
                <div class="box-content padding-bottom-5">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nom de la prestation</th>
                                    <th>Date de début</th>
                                    <th>Durée</th>
                                    <th>Prix</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->pastBookingCollection as $booking) : ?>
                                    <?php /* @var $booking Backend\Entity\Booking */ ?>
                                    <tr>
                                        <td>
                                            <?= $booking->getJobServiceName() ?>
                                        </td>
                                        <td>
                                            <?php $date = new DateTime($booking->getStart()) ?>
                                            Le <b><?= $date->format('d/m/Y') ?></b> à <b><?= $date->format('H') ?>h<?= $date->format('i') ?></b>
                                        </td>
                                        <td>
                                            <?= $booking->getDuration() ?> minutes
                                        </td>
                                        <td>
                                            <?= $booking->getJobServicePrice() ?>€
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php else : ?>
        <div class="alert alert-info">
            Vous n'avez aucune réservation.
        </div>
    <?php endif; ?>
</div>