<?php
    use Application\View\Helper\DisplayAlert;
    
    $this->createProspectForm->setAttribute('class', 'form-horizontal');

    $lastNameElement = $this->createProspectForm->get('last-name');
    $lastNameElement
        ->setAttribute('id', 'signup-last-name')
        ->setAttribute('class', 'form-control')
    ;

    $firstNameElement = $this->createProspectForm->get('first-name');
    $firstNameElement
        ->setAttribute('id', 'signup-first-name')
        ->setAttribute('class', 'form-control')
    ;

    $emailElement = $this->createProspectForm->get('email');
    $emailElement
        ->setAttribute('id', 'signup-email')
        ->setAttribute('class', 'form-control')
    ;

    $phoneElement = $this->createProspectForm->get('phone');
    $phoneElement
        ->setAttribute('id', 'signup-phone')
        ->setAttribute('class', 'form-control')
    ;
?>
<div class="box">
    <div class="box-title-container clearfix">
        <div class="box-title">Création d'un prospect</div>
    </div>
    <div class="box-content pb-5">
        <?= $this->form()->openTag($this->createProspectForm); ?>
        
            <?php if (isset($this->createProspectError) === true) {
                echo $this->displayAlert($this->createProspectError, DisplayAlert::ERROR);
            } ?>
        
            <div class="form-group <?= ($lastNameElement->getMessages()) ? ' has-error' : ''; ?>">
                <label class="col-xs-12 col-sm-3 control-label" for="signup-last-name">Nom</label>
                <div class="col-xs-12 col-sm-8">
                    <?= $this->formText($lastNameElement); ?>
                    <?= $this->displayFormElementErrors($lastNameElement); ?>
                </div>
            </div>
        
            <div class="form-group <?= ($firstNameElement->getMessages()) ? ' has-error' : ''; ?>">
                <label class="col-xs-12 col-sm-3 control-label" for="signup-first-name">Prénom</label>
                <div class="col-xs-12 col-sm-8">
                    <?= $this->formText($firstNameElement); ?>
                    <?= $this->displayFormElementErrors($firstNameElement); ?>
                </div>
            </div>
        
            <div class="form-group <?= ($emailElement->getMessages()) ? ' has-error' : ''; ?>">
                <label class="col-xs-12 col-sm-3 control-label" for="signup-email">Email</label>
                <div class="col-xs-12 col-sm-8">
                    <?= $this->formText($emailElement); ?>
                    <?= $this->displayFormElementErrors($emailElement); ?>
                </div>
            </div>
        
            <div class="form-group <?= ($phoneElement->getMessages()) ? ' has-error' : ''; ?>">
                <label class="col-xs-12 col-sm-3 control-label" for="signup-phone">Téléphone</label>
                <div class="col-xs-12 col-sm-8">
                    <?= $this->formText($phoneElement); ?>
                    <?= $this->displayFormElementErrors($phoneElement); ?>
                </div>
            </div>
            
            <div class="form-group text-right">
                <div class="col-sm-8 col-sm-offset-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check"></i> Enregistrer
                    </button>
                </div>
            </div>
        <?= $this->form()->closeTag($this->createProspectForm); ?>
    </div>
</div>