    <div class="box">
        <div class="box-title-container clearfix">
            <div class="box-tools pull-right">
                <div class="btn-group">
                    <a href="<?= $this->url('administration-prospect/create'); ?>" class="btn btn-primary btn-sm">
                        <i class="fa fa-plus-circle"></i>&nbsp;
                        Nouveau prospect
                    </a>
                </div>
            </div>
            <div class="box-title">Liste des prospects</div>
        </div>
        <div class="box-content">
            <?php if ($this->prospectCollection->count() > 0) : ?>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Identité</th>
                                <th>Adresse e-mail</th>
                                <th>Téléphone</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->prospectCollection as $prospect) : ?>
                            <tr>
                                <td>
                                    <?= $prospect->getFirstName() . ' ' . $prospect->getLastName() ?>
                                </td>
                                <td>
                                    <?= $prospect->getEmail() ?>
                                </td>
                                <td>
                                    <?= $prospect->getPhone() ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else : ?>

                <div class="alert alert-info">
                    Aucun prospect ne répond à cette recherche.
                </div>

            <?php endif; ?>
        </div>

    </div>