<?php $this->headTitle()->set('HAIRLOV.com : Mentions légales'); ?>
<div class="container-fluid image-cover mod-legal" style="height: 30vh"></div>

<div class="container box no-border">
    <div class="box-content">
        <h1>Mentions légales</h1>

        <h2 id="propriete">Propriété</h2>
        <p>Le site diffusé à l’adresse http://www.hairlov.com est la propriété de HL SAS, 75 avenue de Wagram, 75017 Paris.</p>

        <h2>Objet</h2>
        <p>
            Hairlov.com est le premier site de réservation spécialiste de la coiffure.
            Le site Hairlov est destiné à ses membres qui peuvent rechercher, sélectionner et réserver directement des coiffeurs à domicile ou en salon en bénéficiant des remises pouvant aller jusqu’à -50%.
            Hairlov.com se réserve le droit de corriger ou modifier son contenu, à tout moment et sans préavis.
        </p>

        <h2>Responsabilité</h2>
        <p>
            L&#39;utilisateur reconnaît avoir pris connaissance des conditions générales d’utilisation (CGU) et s&#39;engage à les respecter.
            <br>Toutes les informations fournies le sont à titre indicatif et ne dispensent en aucun cas l&#39;utilisateur d&#39;une analyse complémentaire et personnalisée.
            <br>Hairlov.com ne saurait garantir l&#39;exactitude des informations présentes sur son site.
            <br>En conséquence, l&#39;utilisateur reconnaît utiliser ces informations sous sa seule responsabilité. L&#39;utilisateur du site internet hairlov.com reconnaît disposer des capacités nécessaires pour accéder et utiliser ce site.
            <br>Hairlov.com ne saurait être tenue pour responsable des erreurs, d&#39;une indisponibilité des fonctionnalités ou de la présence de virus sur son site internet.
        </p>

        <h2>CNIL</h2>
        <p>Chaque utilisateur dispose d&#39;un droit d&#39;accès, de modification, de rectification et de suppression de ses données personnelles (art.34 de la loi &quot;Informatique et Libertés&quot; n° 78-17 du 16 janvier 1978).
            Pour exercer ce droit, merci de contacter HL SAS, 75 avenue de Wagram, 75017 Paris.
        </p>

        <h2 id="hebergement">Hébergement</h2>
        <p>Le site est hébergé par :</p>

        <blockquote>
            <p>Wixiweb, SARL ayant son siège social au :<br>
            80, rue Michel Richard Delalande, 76000 Rouen<br>
            N° SIRET : 53400740600018<br>
            Rouen B 534 007 406<br>
            Site internet : <a href="http://www.wixiweb.fr">http://www.wixiweb.fr</a><br>
            Téléphone/Fax : 09.72.11.34.68<br>
            <a href="http://www.wixiweb.fr/contact">Formulaire de contact</a></p>
        </blockquote>

        <h2 id="credits">Crédits</h2>
        <p>Ce site a été conçu et réalisé par <a href="http://wixiweb.fr" target="_blank">Wixiweb</a></p>
    </div>
</div>

<div class="container box no-border">
    <div class="box-content">
        <h1 class="margin-bottom-48">Conditions générales d'utilisation</h1>

        <p>Afin d'accéder aux conditions générales d'utilisation, <a href="/CGU_HAIRLOV.doc">téléchargez le document ici</a>.</p>
    </div>
</div>

