<?php
    $idJobServiceElement = $this->uploadJobServiceImageForm->get('job-service-id-job-service');
    $idJobServiceElement
        ->setAttribute('id', 'job-service-id-job-service')
    ;
    
    $this->uploadJobServiceImageForm
            ->setAttribute('action', $this->url('professionnal-job-service/send-image'))
            ->setAttribute('enctype', 'multipart/form-data');

    $jobServiceElement = $this->uploadJobServiceImageForm->get('job-service-image');
    $jobServiceElement
        ->setAttribute('id', 'job-service-image')
    ;
?>

<div class="box">
    <div class="box-title-container clearfix">
        <div class="box-title">Ajout d'images</div>
    </div>
    <div class="box-content pb-5">
        <?= $this->form()->openTag($this->uploadJobServiceImageForm); ?>
            <?= $this->formHidden($idJobServiceElement); ?>

            <div class="alert alert-success alert-dismissible hidden js-job-service-image-upload-success">
                <button type="button" class="close" data-dismiss="alert"><i class="material-icons">&#xE5CD;</i></button>
                Votre image a été envoyé avec succès.
            </div>
        
            <div class="row">
                <div class="col-sm-12">
                <div class="form-group js-job-service-image-upload-dropzone-row">

                    <div class="file-dropzone js-job-service-image-upload-dropzone">
                        <div class="drop-text">Glissez-déposez votre fichier ici</div>
                        <div class="separator-text"><div class="text">ou</div></div>
                        <?= $this->formFile($jobServiceElement); ?>

                        <div class="overlay hidden js-job-service-image-upload-dropzone-overlay">
                            <div class="loading-text">
                                Envoi en cours&hellip;<br />
                                Progression : <span class="js-job-service-image-upload-dropzone-percentage">0</span>%
                            </div>
                        </div>
                    </div>
                    <div class="help-block hidden js-job-service-image-upload-dropzone-error"></div>
                    <div class="text-muted text-small">Fichier autorisés: JPG, JPEG, PNG &mdash; Taille maximale : 10 Mo</div>

                    <?= $this->displayFormElementErrors($jobServiceElement); ?>
                </div>
                </div>
            </div>
        
            
        <?= $this->form()->closeTag($this->uploadJobServiceImageForm); ?>
        
        <div class="row js-job-service-image-list">
                <?php foreach ($this->jobServiceImageList as $jobServiceImage): ?>
                    <div class="col-xs-3 col-sm-3">
                        <div class="thumbnail-with-delete-button overflow-image galerie-item grey">
                            <button data-action="<?= $this->url('professionnal-job-service/delete-image', ['imageId' => $jobServiceImage->getIdJobServiceImage()]) ?>" type="button" class="btn btn-danger delete-image" data-toggle="tooltip" data-placement="top" title="Supprimer"><i class="fa fa-trash"></i></button>
                            <img src="/image/job-service-image/<?= $jobServiceImage->getFilepath() ?>" class="img-responsive" >
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
        hairlov.professionnal.jobService.manageImages.init(<?= $idJobServiceElement->getValue(); ?>);
    });
<?php $this->inlineScript()->captureEnd(); ?>