<?php $this->headTitle()->append('Votre mot de passe'); ?>
<div class="homepage">
    <div class="overlay"></div>
    <div class="container">

        <div class="header-nav clearfix">
            <a href="/" class="header-nav-logo">
                Hairlov<br />
                <span class="baseline">Coiffeurs Privés</span>
            </a>

            <ul class="righ-nav clearfix">
                <li>
                    <a href="<?= $this->url('application-professional-landing-page'); ?>" class="btn btn-no-border border-transparent btn-icon btn-dark">
                        <i class="fa fa-suitcase"></i>
                        Devenir coiffeur privé
                    </a>
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-xs-12 col-md-12 col-lg-12">
                <div class="hero">
                    <h1 class="hero-title">Devenez membre de HAIRLOV.com</h1>
                    <h2 class="hero-subtitle">Nos 2 000 coiffeurs privés s'occupent de vous, à domicile ou en salon</h2>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-5 col-md-offset-7 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
                <div class="login-box">
                    <div class="inner">
                        <h2>Création du mot de passe</h2>
                        
                        <?= $this->displayFlashMessages('error'); ?>
                        <?= $this->displayFlashMessages('success'); ?>
                        
                        <?php
                            $this->newPasswordForm
                                ->setAttribute('id', 'newPasswordForm')
                            ;
                        ?>
                        <?= $this->form()->openTag($this->newPasswordForm); ?>

                            <div class="alert alert-danger hidden js-login-form-error"></div>

                            <?php
                                $passwordElement = $this->newPasswordForm->get('password');
                                $passwordElement
                                    ->setAttribute('id', 'login-password')
                                    ->setAttribute('class', 'form-control input-lg')
                                    ->setAttribute('placeholder', 'Nouveau mot de passe')
                                    ->setAttribute('required', true)
                                ;
                            ?>
                            <div class="form-group <?= ($passwordElement->getMessages()) ? 'has-error' : ''; ?> js-login-form-row">
                                <?= $this->formPassword($passwordElement); ?>
                                <?= $this->displayFormElementErrors($passwordElement); ?>
                            </div>
                            
                            <div class="btn-group" role="group">
                                <button type="submit" class="btn btn-lg btn-primary text-center js-login-form-submit uppercase">
                                    Valider
                                </button>
                            </div>

                            
                        <?= $this->form()->closeTag($this->newPasswordForm); ?>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-3 separated">
                    <img class="img" src="/img/france.png" alt="Carte de la France" />
                    <div class="content">
                        <span class="big">7 500</span><br />
                        professionnels
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 separated">
                    <img class="img" src="/img/accueil-prestation.png" alt="Prestations" />
                    <div class="content">
                        <span class="big">12 200</span><br />
                        prestations
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 separated">
                    <img class="img" src="/img/accueil-salon.png" alt="Salons" />
                    <div class="content">
                        <span class="big">1 800</span><br />
                        salons de coiffure
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <ul>
                        <li><a href="<?= $this->url('application-contact'); ?>">Contact</a></li>
                        <li><a href="<?= $this->url('application-legal'); ?>">CGU / Légal</a></li>
                        <li><a href="<?= $this->url('application-search-job-service'); ?>">Prestations</a></li>
                        <li><a href="<?= $this->url('application-search-professional'); ?>">Coiffeurs</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>